<a href="https://colab.research.google.com/github/GabrielCachoa/Sat-Heuristics/blob/main/SAT_Todas_mis_heur%C3%ADsticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
import timeit
import statistics
import pandas 
import csv
import time
import glob
from os.path import isfile


In [ ]:
import pickle

open_file = open('/content/15queensP.pkl', "rb")
PQueens = pickle.load(open_file)
open_file.close()
pQueens = [15**2,len(PQueens)]

for i in range(len(PQueens)):
  if len(PQueens[i])<15:
    PQueens[i].extend([0]*(15- len(PQueens[i])))

PQueens = np.array(PQueens)

open_file = open('/content/Pcolor.pkl', "rb")
Pcolor = pickle.load(open_file)
open_file.close()
pcolor = [23*5,len(Pcolor)]

for i in range(len(Pcolor)):
  if len(Pcolor[i])<5:
    Pcolor[i].extend([0]*(5- len(Pcolor[i])))

Pcolor = np.array(Pcolor)



(p175,P175) = load('/content/drive/MyDrive/Tesis Gabriel Cachoa/Benchmarks/UF175.753.100/uf175-01.txt')
s=np.random.randint(0,2,p175[0])

# Cargar instancias

p = [ número de vars, número de cláusulas ]

P np.array igual que la matriz dada por la instancia

In [ ]:
def load(fn):
  f = open(fn, 'r')
  data = f.read()
  f.close()
  clauses = []
  lines = data.split("\n")
  p=[]

  for line in lines:
    if len(line) == 0 or line[0] in ['c', '%', '0']:
      continue

    if line[0]=='p':
      problemline=line.split()
      p.extend([int(problemline[2]),int(problemline[3])])
    else:
      clause = [int(x) for x in line.split()[0:-1]]
      clauses.append([x for x in clause])


  P=np.array(clauses)

  return (p,P)


# Búsqueda Local

f(P,s)

como en la definición del latex

Neighborhood(p,s,c,n,seed)

p es la línea del problema
s solución dada (np.array)
c número de cambios (int)
n tamaño de la vec. (int)
seed semilla (int)

In [ ]:
def f(P,s):
  (n,m)=P.shape
  values=np.zeros(n)
  Q=np.copy(P)
  for i in range(n):
    for j in range(m):
      if s[np.abs(Q[i,j])-1]==0:
        Q[i,j]=Q[i,j]*(-1)
    values[i]=np.sign(np.max(Q[i,:]))
  values[values==-1]=0
  return sum(values)

In [ ]:
def Neighborhood(p,s,n,c,seed):
  m=p[0]
  V=np.zeros((n+1,m))
  V[0,:]=s
  random.seed(seed)
  for i in range(1,n+1):
    V[i,:] = s
    for j in range(c):
      c1=random.randint(0,m)
      V[i,c1]=1-V[i,c1]
  return V

---



In [ ]:
def LocalSearch(P,V):
  v=[]
  for i in range(V.shape[0]):
    v.append(f(P,V[i,:]))
  f_star=max(v)
  s_star=V[v.index(max(v))]
  return (f_star,s_star)

In [ ]:
def HillClimbing(P,p,s,n,c,seed,TIME):
  start_time = time.time()
  now_time = time.time()

  s_star = np.copy(s)

  while now_time - start_time < TIME:
    (f_star,s_star) = LocalSearch(P,Neighborhood(p,s_star,n,c,seed))
    s = np.copy(s_star)
    now_time = time.time()
    
  return (f_star,s_star)

In [ ]:
s=np.random.randint(0,2,529)

In [ ]:
s

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [ ]:
f(Phamiltonian,[0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0])

8837.0

In [ ]:
HillClimbing(Phamiltonian,phamiltonian,s,100,3,123456,60)

(8911.0,
 array([0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
        0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
        0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
        0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0.,
        1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
   

## Hil Climbing Analysis


In [ ]:
HillClimbing

# Búsqueda tabú

f(P,s)

Neighborhood(p,s_star,c,n,seed)

In [ ]:
def CleanTheNeighborhood(V,TabuList):

  CleanV = np.copy(V)

  EraseList = []

  for i in range(V.shape[0]):
    for j in range(len(TabuList)):
      if np.array_equal(V[i,:],TabuList[j]):
        EraseList.append(i)
        
  
  for i in range(len(EraseList)):
    if CleanV.shape[0] != 0:
      EraseList[i] = EraseList[i]-i
      CleanV = np.delete(CleanV,EraseList[i],0)
    else:
      break

  return CleanV

In [ ]:
def TabuSearch(P,p,s,n,c,seed,TIME,l):
  start_time=time.time()
  now_time=time.time()

  TabuList=[]
  s_star = np.copy(s)
  f_star = f(P,s) 

  while now_time - start_time < TIME:

    V = Neighborhood(p,s_star,n,c,seed)
    V = CleanTheNeighborhood(V,TabuList)

    if V.shape[0]!=0:

      (f_s,s) = LocalSearch(P,V)
      TabuList.append(s)
      if len(TabuList) > l:
        TabuList.pop(0)
      if f_s > f_star:
        s_star = np.copy(s)
        f_star = f_s
        
      now_time = time.time()

    else:
      now_time = time.time()
  
  return (f_star,s_star)

##Tabu Analysis


In [ ]:
pcolor

[115, 378]

In [ ]:
np.random.seed(1234567)
s=np.random.randint(0,2,115)

In [ ]:
TabuSearch(Pcolor,pcolor,s,100,2,1234567,120,40)

In [ ]:
TabuSearch(Pcolor,pcolor,s,100,2,1234567,240,40)

(366.0,
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.]))

In [ ]:
f(Pcolor,s)

315.0

In [ ]:
s=np.random.randint(0,2,225)

In [ ]:
f(PQueens,s)

4043.0

In [ ]:
TabuSearch(PQueens,pQueens,s,100,2,1234567,120,6)

(4400.0,
 array([0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
        0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1.,
        1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
        1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
        0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
        0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
        0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
   

In [ ]:
TabuSearch(PQueens,pQueens,s,100,2,1234567,240,6)

(4572.0,
 array([0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
        0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
        1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
        0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
        0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
   

# Recocido simulado

f(P,s)

Neighborhood(p,s_star,n,c,seed)

In [ ]:
def SimulatedAnnealing(P,p,s,t,alpha,n,c,seed,TIME):

  s_star = np.copy(s)
  f_star = f(P,s_star)
  
  start_time = time.time()
  now_time = time.time()

  while now_time - start_time < TIME:
    V = Neighborhood(p,s_star,n,c,seed)
    (f_s,s) = LocalSearch(P,V)
    if f_s >= f_star:
      f_star = f_s
      s_star = np.copy(s)

    elif np.exp((f_star - f_star)/t) > random.uniform():
      f_star = f_s
      s_star = np.copy(s)


    t = t* alpha
    now_time=time.time()
  

  return (f_star,s_star)

##Simulated Anneling Analysis

In [ ]:
np.random.seed(1234567)
s=np.random.randint(0,2,225)

In [ ]:
s

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0])

In [ ]:
f(PQueens,s)

4050.0

In [ ]:
SimulatedAnnealing(PQueens,pQueens,s,500,0.15,100,2,1234567,60)

(4192.0,
 array([1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
        0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1.,
   

In [ ]:
SimulatedAnnealing(PQueens,pQueens,s,500,0.15,100,2,1234567,120)

(4317.0,
 array([1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
        0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
   

In [ ]:
np.random.seed(1234567)
s=np.random.randint(0,2,115)

In [ ]:
s

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0])

In [ ]:
f(Pcolor,s)

288.0

In [ ]:
SimulatedAnnealing(Pcolor,pcolor,s,1000,0.2,200,2,1234567,60)

(372.0,
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.]))

In [ ]:
SimulatedAnnealing(Pcolor,pcolor,s,1000,0.2,200,2,1234567,120)

(372.0,
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.]))

# GRASP
f(P,s)

greedy_f(P,s)

S es un conjunto de números enteros 

Candidates(p,S)



Neighborhood(p,s_star,c,n,seed)

SolutionFormat(S)

In [ ]:
def greedy_f(P,S):
  (n,m)=P.shape
  v=np.zeros(n)
  Q=np.copy(P)
  for i in range(n):
    for j in range(m):
      if Q[i,j] in S:
        v[i]=1
        break
  values = sum(v)
  return values



In [ ]:
def Candidates(p,S):
  id_plus = lambda x : x
  id_minus = lambda x : -x

  Range = list(range(1,p[0]+1))

  for i in range(len(S)):
    Range.remove(np.abs(S[i]))

  L = [i(x) for x in Range for i in (id_plus, id_minus)]
  
  return L

In [ ]:
def SolutionFormat(p,S):

  s = np.array([1 if i+1 in S else 0 for i in range(p[0])])
  
  return s



---



In [ ]:
def GreedyConstruction(P,p):
  S = []
  L = Candidates(p,S)
  GreedyValue = [greedy_f(P,[L[i]]) for i in range(len(L))]

  while len(L) != 0:
    Choosen = L[np.argmax(GreedyValue)]
    S.append(Choosen)
    L = Candidates(p,S)
    GreedyValue = [greedy_f(P,[L[i]]) for i in range(len(L))]

  s_star = SolutionFormat(p,S)

  return s_star

In [ ]:
def RCL(P,L,S,alpha):

  S_copy = np.copy(S)
  GreedyValue = [greedy_f(P,[L[i]]) for i in range(len(L))]

  Max = np.max(GreedyValue)
  Min = np.min(GreedyValue)
  value = Max - alpha * (Max - Min)

  CandidatesRestrictedList = []
  for i in range(len(L)):
    if GreedyValue[i] > value:
      CandidatesRestrictedList.append(L[i])

  return CandidatesRestrictedList

In [ ]:
def GreedyRandomizedConstruction(P,p,alpha):
  S = []
  L = Candidates(p,S)
  GreedyValue = [greedy_f(P,[L[i]]) for i in range(len(L))]

  while len(L) != 0:
    
    RCL_list = RCL(P,L,S,alpha)

    if len(RCL_list) != 0:
      index = random.randint(0,len(RCL_list))
      Choosen = RCL_list[index]
      S.append(Choosen)
      L = Candidates(p,S)

    else:
      GreedyValue = [greedy_f(P,[L[i]]) for i in range(len(L))]
      Choosen = L[np.argmax(GreedyValue)]
      S.append(Choosen)
      L = Candidates(p,S)

  s_star = SolutionFormat(p,S)

  return s_star

In [ ]:
def GRASP(P,p,alpha,seed,n,c,TIME):
  start_time = time.time()
  now_time = time.time()

  f_star = 0

  random.seed(seed)

  while now_time - start_time < TIME:

    s0 = GreedyRandomizedConstruction(P,p,alpha)

    V = Neighborhood(p,s0,n,c,seed)
    (f_s1,s1) = LocalSearch(P,V)

    if f_s1 > f_star:
      s_star = np.copy(s1)
      f_star = f_s1

    now_time = time.time()
  
  return (f_star,s_star)

## GRASP Analysis

In [ ]:
np.random.seed(1234567)
s=np.random.randint(0,2,225)
s

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0])

In [ ]:
f(PQueens,s)

4050.0

In [ ]:
GRASP(PQueens,pQueens,0.2,1234567,100,2,60)

(5182.0,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [ ]:
GRASP(PQueens,pQueens,0.2,1234567,100,2,120)

In [ ]:
np.random.seed(1234567)
s=np.random.randint(0,2,115)
s

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0])

In [ ]:
f(Pcolor,s)

288.0

In [ ]:
GRASP(Pcolor,pcolor,0.2,1234567,100,2,60)

(357.0,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [ ]:
GRASP(Pcolor,pcolor,0.2,1234567,100,2,120)

(357.0,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

# Vecindades Variables

Sizes es una lista de listas donde cada elemento es [tamaño de la vecindad, cambios]


InitialSolution(p)


In [ ]:
def InitialSolution(p):
  s = random.randint(0,2,p[0])

  return s



---



In [ ]:
def Shaking(P,p,s_star,k,Sizes,seed):

  V = Neighborhood(p,s_star,Sizes[k][0],Sizes[k][1],seed)
  i = random.randint(0,V.shape[0])

  s_0 = V[i,:]

  return s_0

In [ ]:
def VND(P,p,s,Sizes,seed):

  s_star = np.copy(s)
  f_star = f(P,s)

  l_max = len(Sizes)

  l = 0

  while l < l_max:

    (f_s,s) = LocalSearch(P,Neighborhood(p,s_star,Sizes[l][0],Sizes[l][1],seed))

    if f_s >= f_star:
      s_star = np.copy(s)
      f_star = f_s
      l = l+1

    else:
      l = 0
      

  return (f_star,s_star)

In [ ]:
def VariableNeighborhoodSearch(P,p,Sizes,seed,TIME):
  start_time = time.time()
  now_time = time.time()
  
  
  random.seed(seed)

  s_star = InitialSolution(p)
  f_star = f(P,s_star)

  k_max = len(Sizes)
  k = 0

  while (k < k_max) and (now_time - start_time < TIME):
    s_0 = Shaking(P,p,s_star,k,Sizes,seed)
    (f_s1,s1) = LocalSearch(P,Neighborhood(p,s_star,Sizes[k][0],Sizes[k][1],seed))

    if f_s1 > f_star:
      s_star = np.copy(s1)
      f_star = f_s1

      k = 0
    else:
      
      k = k + 1


    now_time = time.time()

  return (f_star,s_star)


#VNS Analysis

In [ ]:
np.random.randint(1234567)
s=np.random.randint(0,2,225)

In [ ]:
s

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0])

In [ ]:
f(PQueens,s)

3879.0

In [ ]:
Sizes = [[250,2],[225,2],[200,2],[200,1] ]

In [ ]:
VariableNeighborhoodSearch(PQueens,pQueens,Sizes,1234567,60)

(4152.0,
 array([1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
        0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1.,
   

In [ ]:
VariableNeighborhoodSearch(PQueens,pQueens,Sizes,1234567,120)

(4198.0,
 array([1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
        0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1.,
   

In [ ]:
np.random.randint(1234567)
s=np.random.randint(0,2,115)

In [ ]:
s

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1])

In [ ]:
f(Pcolor,s)

304.0

In [ ]:
VariableNeighborhoodSearch(Pcolor,pcolor,Sizes,1234567,60)

(376.0,
 array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [ ]:
VariableNeighborhoodSearch(Pcolor,pcolor,Sizes,1234567,120)

(376.0,
 array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]))

# Algoritmos genéticos

Initialization(P,p,size)

Selection(P,p,Population)

Recombination(P,p,MatingPool)

Mutation(P,p,Offspring)

Replacement(P,p,Population,Offspring)

In [ ]:
def Initialization(P,p,size):

  Population = []
  for i in range(size):
    Population.append(random.randint(0,2,p[0]))
  Population=np.array(Population)

  return Population

In [ ]:
def Selection(P,p,Population,size):

  a=np.arange(Population.shape[0])
  MatingPool=[]
    
  Values = [f(P,Population[i,:]) for i in range(Population.shape[0])]
  sum = np.sum(Values)
  P = [value/sum for value in Values]

  for i in range(int(size/2)):
    MatingPool.append(random.choice(a,2,p))

  return MatingPool

In [ ]:
  def Recombination(P,p,MatingPool,Population):
    Offspring=[]

    for pair in MatingPool:
      n=random.randint(p[0])
      son=np.append(Population[pair[0],0:n],Population[pair[1],n:p[0]])
      Offspring.append(son)

    return Offspring

In [ ]:
def Recombination(P,p,MatingPool,Population):

  Offspring=[]
  for pair in MatingPool:
    key=random.randint(0,2,p[0])
    son=[]
    for i in range(p[0]):
      if key[i]==0:
        son.append(Population[pair[0],i])
      else:
        son.append(Population[pair[1],i])
    son=np.array(son)
    Offspring.append(son)
  return Offspring

In [ ]:
def Mutation(P,p,Offspring):

  M=random.uniform(0,1,len(Offspring))
  M[M > 0.2]=0
  M[M != 0]=1

  for i in range(len(Offspring)):
    if M[i]==1:
      l=Offspring[i].shape[0]
      n=random.randint(l)
      Offspring[i][n]=1-Offspring[i][n]

  return Offspring


In [ ]:
def Replacement(P,p,Population,Offspring,size):
  new_population=[]
  for i in range(size):
    new_population.append(np.append(Population[i,:],f(P,Population[i,:])))

  new_population=np.array(new_population)
  new_population = new_population[np.argsort(new_population[:, -1])]
  new_population=np.delete(new_population,-1,1)
  new_population=np.delete(new_population,range(int(size/2)),0)

  for son in Offspring:
    new_population=tuple(new_population)
    new_population=np.vstack((new_population,son))
    
  new_population=np.array(new_population)
  return Population



---



In [ ]:
def GeneticAlgorithm(P,p,size,seed,TIME):
  
  start_time = time.time()
  now_time = time.time()

  random.seed(seed)

  Population = Initialization(P,p,size)


  while now_time - start_time < TIME:


    MatingPool = Selection(P,p,Population,size)

    Offspring = Recombination(P,p,MatingPool,Population)

    Offspring = Mutation(P,p,Offspring)

    Population = Replacement(P,p,Population,Offspring,size)

    now_time = time.time()
  
  (f_star,s_star) = LocalSearch(P,Population)

  return (f_star,s_star) 


#GA Analysis

In [ ]:
GeneticAlgorithm(PQueens,pQueens,150,123456,60)

(4361.0,
 array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0]))

In [ ]:
GeneticAlgorithm(PQueens,pQueens,50,123456,60)

(4245.0,
 array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 1, 1, 0, 1]))

In [ ]:
GeneticAlgorithm(PQueens,pQueens,100,1234567,120)

(4392.0,
 array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0]))

In [ ]:
GeneticAlgorithm(Pcolor,pcolor,50,1234567,60)

(323.0,
 array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 1, 0, 0, 0]))

In [ ]:
GeneticAlgorithm(Pcolor,pcolor,100,123457,60)

(317.0,
 array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 1, 0]))

In [ ]:
GeneticAlgorithm(Pcolor,pcolor,150,12367,60)

(328.0,
 array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1]))

# Optimización por colonias de hormigas

PheromonesInitialization(p)

ProbabilitiesMatrix(p,Pheromones)

Candidates(p,S)

Choose(L,Probabilities)



In [ ]:
def PheromonesInitialization(p):

  Pheromones = np.full((2*p[0]+1,2*p[0]+1),0.5)

  L = Candidates(p,[])

  for i in range(2*p[0]+1):
    for j in range(2*p[0]+1):
      
      if j > 0:
        Pheromones[0,j] = L[j-1]

      if i == j:
        Pheromones[i,j] = 0
      elif (i%2) == 0 and j == i-1:
        Pheromones[i,j] = 0
      elif (i%2) != 0 and j == i+1:
        Pheromones[i,j] = 0
    
    if i > 0:
      Pheromones[i,0] = L[i-1]


  return Pheromones

In [ ]:
def ProbabilitiesInitialization(p):
  Probabilities = np.full((2*p[0]+1,2*p[0]+1),1 / (p[0]-2))

  L = Candidates(p,[])

  for i in range(2*p[0]+1):
    for j in range(2*p[0]+1):
      
      if j > 0:
        Probabilities[0,j] = L[j-1]

      if i == j:
        Probabilities[i,j] = 0
      elif (i%2) == 0 and j == i-1:
        Probabilities[i,j] = 0
      elif (i%2) != 0 and j == i+1:
        Probabilities[i,j] = 0
    
    if i > 0:
      Probabilities[i,0] = L[i-1]
  return Probabilities

In [ ]:
def Choose(p,S,L,Probabilities):
 
  ALLCandidates = Probabilities[:,0]
  ActualPosition = np.where(ALLCandidates == S[-1])[0]
  RowOfProbabilities = Probabilities[ActualPosition,:]
  
  ProbabilitiesL = []

  for i in range(len(L)):
    index = np.where(ALLCandidates == L[i])[0][0]
    ProbabilitiesL.append(RowOfProbabilities[0,index])
  
  Sum = np.sum(ProbabilitiesL)
  
  NormalizedProbabilities = [p/Sum for p in ProbabilitiesL]

  Choosen = random.choice(L,p = NormalizedProbabilities, size = 1)[0]

  return Choosen

In [ ]:
def PheromonesIntensification(Pheromones,BestWalk,delta):
  ALLCandidates = Pheromones[:,0]
  for i in range(len(BestWalk)-1):
    index0 = np.where(ALLCandidates == BestWalk[i])[0][0]
    index1 = np.where(ALLCandidates == BestWalk[i+1])[0][0]

    Pheromones[index0,index1] = Pheromones[index0,index1] + delta
    
  return Pheromones

In [ ]:
def ProbabilitiesMatrix(Probabilities,Pheromones):
  for i in range(1,Probabilities.shape[0]):
    Sum = np.sum(Pheromones[i,1:])
    for j in range(1,Probabilities.shape[1]):
      Probabilities[i,j] = Pheromones[i,j] / Sum
  
  return Probabilities



---



In [ ]:
def AntColonyOptimization(P,p,k,rho,delta,seed,TIME):

  start_time = time.time()
  now_time = time.time()

  random.seed(seed)

  Pheromones = PheromonesInitialization(p)

  Probabilities = ProbabilitiesInitialization(p)

  random.seed(seed)

  while now_time - start_time < TIME:

    Solutions = []
    Walks = []
    for i in range(5):
      S = []
      L = Candidates(p,S)
      
      S.append(L[random.randint(len(L))])

      while len(L) != 0:
        Choosen = Choose(p,S,L,Probabilities)
        S.append(Choosen)
        L = Candidates(p,S)

      s = SolutionFormat(p,S)
      Solutions.append(s)
      Walks.append(S)

    Values = [f(P,s) for s in Solutions]

    BestWalk = Walks[Values.index(max(Values))]

    s_star = Solutions[Values.index(max(Values))]
    f_star = max(Values)

    for i in range(1,Pheromones.shape[0]):
      for j in range(1,Pheromones.shape[1]):
        Pheromones[i,j] = Pheromones[i,j] * (1-rho) 


    Pheromones = PheromonesIntensification(Pheromones,BestWalk,delta)

    Probabilities = ProbabilitiesMatrix(Probabilities,Pheromones)

    now_time = time.time()


  return (f_star,s_star)





## OCA Analysis

In [ ]:
np.random.randint(1234567)

In [ ]:
AntColonyOptimization(PQueens,pQueens,50,0.2,0.15,1234567,60)

(4073.0,
 array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
        0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 1, 0]))

In [ ]:
AntColonyOptimization(PQueens,pQueens,50,0.2,0.15,1234567,120)

(4144.0,
 array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0]))

In [ ]:
AntColonyOptimization(PQueens,pQueens,50,0.2,0.15,1234567,240)

(4435.0,
 array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0]))

In [ ]:
AntColonyOptimization(Pcolor,pcolor,10,0.15,0.15,1234567,60)

(344.0,
 array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        0, 1, 0, 0, 0]))

In [ ]:
AntColonyOptimization(Pcolor,pcolor,10,0.15,0.15,1234567,120)

(356.0,
 array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0]))

In [ ]:
AntColonyOptimization(Pcolor,pcolor,10,0.15,0.15,1234567,240)

(357.0,
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 1]))